#!/bin/sh

# sbin/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

sbin/bootstrap

echo "==> Updating db…"
bin/hanami db create

bin/hanami db create -e test
bin/hanami db reset -e test

bin/hanami db migrate
